# Core Settings For Project Octopus

site.name:
  desc: The name of this website.
  default: My Awesome Project Octopus Site

site.theme.*:
  desc: The theme to use. To set the theme for a specific path, use the setting site.theme.your.path
  default: default
