# Core Settings For Project Octopus

site.name:
  desc: The name of this website.
  default_func: guess_site_name

site.slogan:
	desc: This site's slogan (sometimes displayed in the header).
	default: An Octopus app

site.theme.*:
  desc: The theme to use. To set the theme for a specific path, use the setting site.theme.your.path
  default: default

site.default_password_length:
  default: 12
